/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Subscription = {
  _id: string;
  _type: "subscription";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  email?: string;
  status?: "active" | "unsubscribed" | "pending";
  subscribedAt?: string;
  unsubscribedAt?: string;
  source?: "footer" | "popup" | "checkout" | "other";
  ipAddress?: string;
  userAgent?: string;
};

export type Review = {
  _id: string;
  _type: "review";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  product?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "product";
  };
  user?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "user";
  };
  rating?: number;
  title?: string;
  content?: string;
  isVerifiedPurchase?: boolean;
  status?: "pending" | "approved" | "rejected";
  helpful?: number;
  helpfulBy?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "user";
  }>;
  adminNotes?: string;
  createdAt?: string;
  updatedAt?: string;
  approvedAt?: string;
  approvedBy?: string;
};

export type UserAccessRequest = {
  _id: string;
  _type: "userAccessRequest";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  clerkUserId?: string;
  email?: string;
  firstName?: string;
  lastName?: string;
  status?: "pending" | "approved" | "rejected";
  requestedAt?: string;
  approvedAt?: string;
  approvedBy?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "user";
  };
  rejectedAt?: string;
  rejectedBy?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "user";
  };
  notes?: string;
};

export type SentNotification = {
  _id: string;
  _type: "sentNotification";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  notificationId?: string;
  title?: string;
  message?: string;
  type?: "promo" | "order" | "system" | "marketing" | "general";
  priority?: "low" | "medium" | "high" | "urgent";
  sentAt?: string;
  sentBy?: string;
  actionUrl?: string;
  recipientCount?: number;
  recipients?: Array<{
    email?: string;
    name?: string;
    delivered?: boolean;
    read?: boolean;
    readAt?: string;
    _key: string;
  }>;
};

export type Contact = {
  _id: string;
  _type: "contact";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  email?: string;
  subject?: string;
  message?: string;
  status?: "new" | "read" | "replied" | "closed";
  priority?: "low" | "medium" | "high" | "urgent";
  submittedAt?: string;
  ipAddress?: string;
  userAgent?: string;
};

export type Address = {
  _id: string;
  _type: "address";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  email?: string;
  user?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "user";
  };
  phone?: string;
  address?: string;
  city?: string;
  state?: string;
  zip?: string;
  country?: string;
  countryCode?: string;
  stateCode?: string;
  subArea?: string;
  type?: "home" | "office" | "other";
  default?: boolean;
  createdAt?: string;
};

export type User = {
  _id: string;
  _type: "user";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  clerkUserId?: string;
  email?: string;
  firstName?: string;
  lastName?: string;
  phone?: string;
  dateOfBirth?: string;
  profileImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  addresses?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "address";
  }>;
  preferences?: {
    newsletter?: boolean;
    emailNotifications?: boolean;
    smsNotifications?: boolean;
    preferredCurrency?: "USD" | "EUR" | "GBP" | "CAD";
    preferredLanguage?: "en" | "es" | "fr" | "de";
  };
  rewardPoints?: number;
  wishlist?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "product";
  }>;
  cart?: Array<{
    product?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "product";
    };
    quantity?: number;
    addedAt?: string;
    size?: string;
    color?: string;
    _key: string;
  }>;
  orders?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "order";
  }>;
  loyaltyPoints?: number;
  totalSpent?: number;
  walletBalance?: number;
  walletTransactions?: Array<{
    id?: string;
    type?: "credit_refund" | "credit_manual" | "debit_order" | "debit_withdrawal";
    amount?: number;
    balanceBefore?: number;
    balanceAfter?: number;
    description?: string;
    orderId?: string;
    withdrawalRequestId?: string;
    processedBy?: string;
    createdAt?: string;
    status?: "completed" | "pending" | "failed" | "cancelled";
    _key: string;
  }>;
  withdrawalRequests?: Array<{
    id?: string;
    amount?: number;
    method?: "bank" | "paypal" | "stripe" | "check";
    bankDetails?: {
      accountHolderName?: string;
      bankName?: string;
      accountNumber?: string;
      routingNumber?: string;
      swiftCode?: string;
    };
    paypalEmail?: string;
    status?: "pending" | "approved" | "processing" | "completed" | "rejected" | "cancelled";
    requestedAt?: string;
    processedAt?: string;
    processedBy?: string;
    rejectionReason?: string;
    notes?: string;
    transactionId?: string;
    _key: string;
  }>;
  lastLogin?: string;
  isActive?: boolean;
  premiumStatus?: "none" | "pending" | "active" | "rejected" | "cancelled";
  premiumAppliedAt?: string;
  premiumApprovedBy?: string;
  premiumApprovedAt?: string;
  premiumRejectedAt?: string;
  rejectionReason?: string;
  isBusiness?: boolean;
  businessStatus?: "none" | "pending" | "active" | "rejected" | "cancelled";
  businessApprovedBy?: string;
  businessApprovedAt?: string;
  businessRejectedAt?: string;
  businessAppliedAt?: string;
  membershipType?: "standard" | "premium" | "business" | "vip";
  activatedAt?: string;
  activatedBy?: string;
  role?: "user" | "admin" | "seller" | "employee";
  isEmployee?: boolean;
  isAdmin?: boolean;
  employeeRole?: "callcenter" | "packer" | "warehouse" | "deliveryman" | "incharge" | "accounts";
  employeeStatus?: "active" | "inactive" | "suspended";
  employeeAssignedBy?: string;
  employeeAssignedAt?: string;
  employeeSuspendedBy?: string;
  employeeSuspendedAt?: string;
  employeeSuspensionReason?: string;
  employeePerformance?: {
    ordersProcessed?: number;
    ordersConfirmed?: number;
    ordersPacked?: number;
    ordersAssignedForDelivery?: number;
    ordersDelivered?: number;
    cashCollected?: number;
    paymentsReceived?: number;
    lastActiveAt?: string;
  };
  createdAt?: string;
  updatedAt?: string;
  notifications?: Array<{
    id?: string;
    title?: string;
    message?: string;
    type?: "promo" | "order" | "system" | "marketing" | "general";
    read?: boolean;
    priority?: "low" | "medium" | "high" | "urgent";
    sentAt?: string;
    readAt?: string;
    sentBy?: string;
    actionUrl?: string;
    _key: string;
  }>;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Blogcategory = {
  _id: string;
  _type: "blogcategory";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Blog = {
  _id: string;
  _type: "blog";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  author?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "author";
  };
  mainImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  blogcategories?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "blogcategory";
  }>;
  publishedAt?: string;
  isLatest?: boolean;
  body?: BlockContent;
};

export type BlockContent = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote";
  listItem?: "bullet";
  markDefs?: Array<{
    href?: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
} | {
  asset?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
  };
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  _type: "image";
  _key: string;
}>;

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  bio?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type Banner = {
  _id: string;
  _type: "banner";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  badge?: string;
  discountAmount?: number;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Order = {
  _id: string;
  _type: "order";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderNumber?: string;
  invoice?: {
    id?: string;
    number?: string;
    hosted_invoice_url?: string;
  };
  stripeCheckoutSessionId?: string;
  stripeCustomerId?: string;
  clerkUserId?: string;
  clerkPaymentId?: string;
  clerkPaymentStatus?: string;
  customerName?: string;
  email?: string;
  stripePaymentIntentId?: string;
  products?: Array<{
    product?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "product";
    };
    quantity?: number;
    _key: string;
  }>;
  subtotal?: number;
  tax?: number;
  shipping?: number;
  totalPrice?: number;
  currency?: string;
  amountDiscount?: number;
  address?: {
    state?: string;
    zip?: string;
    city?: string;
    address?: string;
    name?: string;
  };
  status?: "pending" | "address_confirmed" | "order_confirmed" | "packed" | "ready_for_delivery" | "out_for_delivery" | "delivered" | "completed" | "cancelled" | "rescheduled" | "failed_delivery";
  orderDate?: string;
  paymentStatus?: "pending" | "paid" | "failed" | "cancelled";
  paymentMethod?: "cash_on_delivery" | "stripe" | "clerk" | "card";
  addressConfirmedBy?: string;
  addressConfirmedAt?: string;
  orderConfirmedBy?: string;
  orderConfirmedAt?: string;
  packedBy?: string;
  packedAt?: string;
  packingNotes?: string;
  assignedWarehouseBy?: string;
  assignedWarehouseAt?: string;
  dispatchedBy?: string;
  dispatchedAt?: string;
  assignedDeliverymanId?: string;
  assignedDeliverymanName?: string;
  deliveredBy?: string;
  deliveredAt?: string;
  deliveryNotes?: string;
  deliveryAttempts?: number;
  rescheduledDate?: string;
  rescheduledReason?: string;
  cashCollected?: boolean;
  cashCollectedAmount?: number;
  cashCollectedAt?: string;
  cashSubmittedToAccounts?: boolean;
  cashSubmittedBy?: string;
  cashSubmittedAt?: string;
  cashSubmissionNotes?: string;
  assignedAccountsEmployeeId?: string;
  assignedAccountsEmployeeName?: string;
  cashSubmissionStatus?: "not_submitted" | "pending" | "confirmed" | "rejected";
  cashSubmissionRejectionReason?: string;
  paymentReceivedBy?: string;
  paymentReceivedAt?: string;
  cancellationRequested?: boolean;
  cancellationRequestedAt?: string;
  cancellationRequestReason?: string;
  cancelledAt?: string;
  cancelledBy?: string;
  cancellationReason?: string;
  amountPaid?: number;
  refundedToWallet?: boolean;
  refundAmount?: number;
  statusHistory?: Array<{
    status?: string;
    changedBy?: string;
    changedByRole?: "admin" | "callcenter" | "packer" | "warehouse" | "deliveryman" | "incharge" | "accounts" | "system";
    changedAt?: string;
    notes?: string;
    _key: string;
  }>;
};

export type Product = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  images?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  description?: string;
  price?: number;
  discount?: number;
  categories?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "category";
  }>;
  stock?: number;
  brand?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "brand";
  };
  status?: "new" | "hot" | "sale";
  variant?: "gadget" | "appliances" | "refrigerators" | "others";
  isFeatured?: boolean;
  averageRating?: number;
  totalReviews?: number;
  ratingDistribution?: {
    fiveStars?: number;
    fourStars?: number;
    threeStars?: number;
    twoStars?: number;
    oneStar?: number;
  };
};

export type Brand = {
  _id: string;
  _type: "brand";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  range?: number;
  featured?: boolean;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = Subscription | Review | UserAccessRequest | SentNotification | Contact | Address | User | SanityImageCrop | SanityImageHotspot | Blogcategory | Slug | Blog | BlockContent | Author | Banner | Order | Product | Brand | Category | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./app/(client)/(user)/success/page.tsx
// Variable: query
// Query: *[_type == 'order' && clerkUserId == $userId] | order(orderDate desc){  ...,products[]{    ...,product->  }}
export type QueryResult = Array<{
  _id: string;
  _type: "order";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderNumber?: string;
  invoice?: {
    id?: string;
    number?: string;
    hosted_invoice_url?: string;
  };
  stripeCheckoutSessionId?: string;
  stripeCustomerId?: string;
  clerkUserId?: string;
  clerkPaymentId?: string;
  clerkPaymentStatus?: string;
  customerName?: string;
  email?: string;
  stripePaymentIntentId?: string;
  products: Array<{
    product: {
      _id: string;
      _type: "product";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      name?: string;
      slug?: Slug;
      images?: Array<{
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }>;
      description?: string;
      price?: number;
      discount?: number;
      categories?: Array<{
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        _key: string;
        [internalGroqTypeReferenceTo]?: "category";
      }>;
      stock?: number;
      brand?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "brand";
      };
      status?: "hot" | "new" | "sale";
      variant?: "appliances" | "gadget" | "others" | "refrigerators";
      isFeatured?: boolean;
      averageRating?: number;
      totalReviews?: number;
      ratingDistribution?: {
        fiveStars?: number;
        fourStars?: number;
        threeStars?: number;
        twoStars?: number;
        oneStar?: number;
      };
    } | null;
    quantity?: number;
    _key: string;
  }> | null;
  subtotal?: number;
  tax?: number;
  shipping?: number;
  totalPrice?: number;
  currency?: string;
  amountDiscount?: number;
  address?: {
    state?: string;
    zip?: string;
    city?: string;
    address?: string;
    name?: string;
  };
  status?: "address_confirmed" | "cancelled" | "completed" | "delivered" | "failed_delivery" | "order_confirmed" | "out_for_delivery" | "packed" | "pending" | "ready_for_delivery" | "rescheduled";
  orderDate?: string;
  paymentStatus?: "cancelled" | "failed" | "paid" | "pending";
  paymentMethod?: "card" | "cash_on_delivery" | "clerk" | "stripe";
  addressConfirmedBy?: string;
  addressConfirmedAt?: string;
  orderConfirmedBy?: string;
  orderConfirmedAt?: string;
  packedBy?: string;
  packedAt?: string;
  packingNotes?: string;
  assignedWarehouseBy?: string;
  assignedWarehouseAt?: string;
  dispatchedBy?: string;
  dispatchedAt?: string;
  assignedDeliverymanId?: string;
  assignedDeliverymanName?: string;
  deliveredBy?: string;
  deliveredAt?: string;
  deliveryNotes?: string;
  deliveryAttempts?: number;
  rescheduledDate?: string;
  rescheduledReason?: string;
  cashCollected?: boolean;
  cashCollectedAmount?: number;
  cashCollectedAt?: string;
  cashSubmittedToAccounts?: boolean;
  cashSubmittedBy?: string;
  cashSubmittedAt?: string;
  cashSubmissionNotes?: string;
  assignedAccountsEmployeeId?: string;
  assignedAccountsEmployeeName?: string;
  cashSubmissionStatus?: "confirmed" | "not_submitted" | "pending" | "rejected";
  cashSubmissionRejectionReason?: string;
  paymentReceivedBy?: string;
  paymentReceivedAt?: string;
  cancellationRequested?: boolean;
  cancellationRequestedAt?: string;
  cancellationRequestReason?: string;
  cancelledAt?: string;
  cancelledBy?: string;
  cancellationReason?: string;
  amountPaid?: number;
  refundedToWallet?: boolean;
  refundAmount?: number;
  statusHistory?: Array<{
    status?: string;
    changedBy?: string;
    changedByRole?: "accounts" | "admin" | "callcenter" | "deliveryman" | "incharge" | "packer" | "system" | "warehouse";
    changedAt?: string;
    notes?: string;
    _key: string;
  }>;
}>;

// Source: ./sanity/helpers/index.ts
// Variable: PRODUCT_BY_CATEGORY_QUERY
// Query: *[_type == 'product' && references(*[_type == "category" && slug.current == $categorySlug]._id)] | order(name asc)
export type PRODUCT_BY_CATEGORY_QUERYResult = Array<{
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  images?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  description?: string;
  price?: number;
  discount?: number;
  categories?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "category";
  }>;
  stock?: number;
  brand?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "brand";
  };
  status?: "hot" | "new" | "sale";
  variant?: "appliances" | "gadget" | "others" | "refrigerators";
  isFeatured?: boolean;
  averageRating?: number;
  totalReviews?: number;
  ratingDistribution?: {
    fiveStars?: number;
    fourStars?: number;
    threeStars?: number;
    twoStars?: number;
    oneStar?: number;
  };
}>;
// Variable: SALE_QUERY
// Query: *[_type == 'sale'] | order(name asc)
export type SALE_QUERYResult = Array<never>;
// Variable: MY_ORDERS_QUERY
// Query: *[_type == 'order' && clerkUserId == $userId] | order(orderDate desc)[$start...$end]{    ...,    paymentStatus,    paymentMethod,    products[]{      ...,      product->{        _id,        name,        slug,        image,        images,        price,        currency      }    }  }
export type MY_ORDERS_QUERYResult = Array<{
  _id: string;
  _type: "order";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderNumber?: string;
  invoice?: {
    id?: string;
    number?: string;
    hosted_invoice_url?: string;
  };
  stripeCheckoutSessionId?: string;
  stripeCustomerId?: string;
  clerkUserId?: string;
  clerkPaymentId?: string;
  clerkPaymentStatus?: string;
  customerName?: string;
  email?: string;
  stripePaymentIntentId?: string;
  products: Array<{
    product: {
      _id: string;
      name: string | null;
      slug: Slug | null;
      image: null;
      images: Array<{
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }> | null;
      price: number | null;
      currency: null;
    } | null;
    quantity?: number;
    _key: string;
  }> | null;
  subtotal?: number;
  tax?: number;
  shipping?: number;
  totalPrice?: number;
  currency?: string;
  amountDiscount?: number;
  address?: {
    state?: string;
    zip?: string;
    city?: string;
    address?: string;
    name?: string;
  };
  status?: "address_confirmed" | "cancelled" | "completed" | "delivered" | "failed_delivery" | "order_confirmed" | "out_for_delivery" | "packed" | "pending" | "ready_for_delivery" | "rescheduled";
  orderDate?: string;
  paymentStatus: "cancelled" | "failed" | "paid" | "pending" | null;
  paymentMethod: "card" | "cash_on_delivery" | "clerk" | "stripe" | null;
  addressConfirmedBy?: string;
  addressConfirmedAt?: string;
  orderConfirmedBy?: string;
  orderConfirmedAt?: string;
  packedBy?: string;
  packedAt?: string;
  packingNotes?: string;
  assignedWarehouseBy?: string;
  assignedWarehouseAt?: string;
  dispatchedBy?: string;
  dispatchedAt?: string;
  assignedDeliverymanId?: string;
  assignedDeliverymanName?: string;
  deliveredBy?: string;
  deliveredAt?: string;
  deliveryNotes?: string;
  deliveryAttempts?: number;
  rescheduledDate?: string;
  rescheduledReason?: string;
  cashCollected?: boolean;
  cashCollectedAmount?: number;
  cashCollectedAt?: string;
  cashSubmittedToAccounts?: boolean;
  cashSubmittedBy?: string;
  cashSubmittedAt?: string;
  cashSubmissionNotes?: string;
  assignedAccountsEmployeeId?: string;
  assignedAccountsEmployeeName?: string;
  cashSubmissionStatus?: "confirmed" | "not_submitted" | "pending" | "rejected";
  cashSubmissionRejectionReason?: string;
  paymentReceivedBy?: string;
  paymentReceivedAt?: string;
  cancellationRequested?: boolean;
  cancellationRequestedAt?: string;
  cancellationRequestReason?: string;
  cancelledAt?: string;
  cancelledBy?: string;
  cancellationReason?: string;
  amountPaid?: number;
  refundedToWallet?: boolean;
  refundAmount?: number;
  statusHistory?: Array<{
    status?: string;
    changedBy?: string;
    changedByRole?: "accounts" | "admin" | "callcenter" | "deliveryman" | "incharge" | "packer" | "system" | "warehouse";
    changedAt?: string;
    notes?: string;
    _key: string;
  }>;
}>;
// Variable: COUNT_QUERY
// Query: count(*[_type == 'order' && clerkUserId == $userId])
export type COUNT_QUERYResult = number;

// Source: ./sanity/queries/query.ts
// Variable: BANNER_QUERY
// Query: *[_type == 'banner'] | order(publishedAt desc)
export type BANNER_QUERYResult = Array<{
  _id: string;
  _type: "banner";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  badge?: string;
  discountAmount?: number;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
}>;
// Variable: FEATURED_CATEGORY_QUERY
// Query: *[_type == 'category' && featured == true] | order(name desc)
export type FEATURED_CATEGORY_QUERYResult = Array<{
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  range?: number;
  featured?: boolean;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
}>;
// Variable: ALL_PRODUCTS_QUERY
// Query: *[_type=="product"] | order(name asc)
export type ALL_PRODUCTS_QUERYResult = Array<{
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  images?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  description?: string;
  price?: number;
  discount?: number;
  categories?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "category";
  }>;
  stock?: number;
  brand?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "brand";
  };
  status?: "hot" | "new" | "sale";
  variant?: "appliances" | "gadget" | "others" | "refrigerators";
  isFeatured?: boolean;
  averageRating?: number;
  totalReviews?: number;
  ratingDistribution?: {
    fiveStars?: number;
    fourStars?: number;
    threeStars?: number;
    twoStars?: number;
    oneStar?: number;
  };
}>;
// Variable: DEAL_PRODUCTS
// Query: *[_type == 'product' && status == 'hot'] | order(name asc){  ...,"categories": categories[]->title}
export type DEAL_PRODUCTSResult = Array<{
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  images?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  description?: string;
  price?: number;
  discount?: number;
  categories: Array<string | null> | null;
  stock?: number;
  brand?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "brand";
  };
  status?: "hot" | "new" | "sale";
  variant?: "appliances" | "gadget" | "others" | "refrigerators";
  isFeatured?: boolean;
  averageRating?: number;
  totalReviews?: number;
  ratingDistribution?: {
    fiveStars?: number;
    fourStars?: number;
    threeStars?: number;
    twoStars?: number;
    oneStar?: number;
  };
}>;
// Variable: FEATURE_PRODUCTS
// Query: *[_type == 'product' && isFeatured == true] | order(name asc){  ...,"categories": categories[]->title}
export type FEATURE_PRODUCTSResult = Array<{
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  images?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  description?: string;
  price?: number;
  discount?: number;
  categories: Array<string | null> | null;
  stock?: number;
  brand?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "brand";
  };
  status?: "hot" | "new" | "sale";
  variant?: "appliances" | "gadget" | "others" | "refrigerators";
  isFeatured?: boolean;
  averageRating?: number;
  totalReviews?: number;
  ratingDistribution?: {
    fiveStars?: number;
    fourStars?: number;
    threeStars?: number;
    twoStars?: number;
    oneStar?: number;
  };
}>;
// Variable: BRANDS_QUERY
// Query: *[_type=='brand'] | order(name asc)
export type BRANDS_QUERYResult = Array<{
  _id: string;
  _type: "brand";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
}>;
// Variable: LATEST_BLOG_QUERY
// Query: *[_type == 'blog' && isLatest == true]|order(name asc){    ...,    blogcategories[]->{    title  }  }
export type LATEST_BLOG_QUERYResult = Array<{
  _id: string;
  _type: "blog";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  author?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "author";
  };
  mainImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  blogcategories: Array<{
    title: string | null;
  }> | null;
  publishedAt?: string;
  isLatest?: boolean;
  body?: BlockContent;
}>;
// Variable: GET_ALL_BLOG
// Query: *[_type == 'blog'] | order(publishedAt desc)[0...$quantity]{  ...,       blogcategories[]->{    title}    }
export type GET_ALL_BLOGResult = Array<{
  _id: string;
  _type: "blog";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  author?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "author";
  };
  mainImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  blogcategories: Array<{
    title: string | null;
  }> | null;
  publishedAt?: string;
  isLatest?: boolean;
  body?: BlockContent;
}>;
// Variable: SINGLE_BLOG_QUERY
// Query: *[_type == "blog" && slug.current == $slug][0]{  ...,     author->{    name,    image,  },  blogcategories[]->{    title,    "slug": slug.current,  },}
export type SINGLE_BLOG_QUERYResult = {
  _id: string;
  _type: "blog";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  author: {
    name: string | null;
    image: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
  mainImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  blogcategories: Array<{
    title: string | null;
    slug: string | null;
  }> | null;
  publishedAt?: string;
  isLatest?: boolean;
  body?: BlockContent;
} | null;
// Variable: BLOG_CATEGORIES
// Query: *[_type == "blog"]{     blogcategories[]->{    ...    }  }
export type BLOG_CATEGORIESResult = Array<{
  blogcategories: Array<{
    _id: string;
    _type: "blogcategory";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    title?: string;
    slug?: Slug;
    description?: string;
  }> | null;
}>;
// Variable: OTHERS_BLOG_QUERY
// Query: *[  _type == "blog"  && defined(slug.current)  && slug.current != $slug]|order(publishedAt desc)[0...$quantity]{...  publishedAt,  title,  mainImage,  slug,  author->{    name,    image,  },  categories[]->{    title,    "slug": slug.current,  }}
export type OTHERS_BLOG_QUERYResult = Array<{
  title: string | null;
  mainImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  slug: Slug | null;
  author: {
    name: string | null;
    image: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
  categories: null;
}>;
// Variable: ADDRESS_QUERY
// Query: *[_type=="address"] | order(publishedAt desc)
export type ADDRESS_QUERYResult = Array<{
  _id: string;
  _type: "address";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  email?: string;
  user?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "user";
  };
  phone?: string;
  address?: string;
  city?: string;
  state?: string;
  zip?: string;
  country?: string;
  countryCode?: string;
  stateCode?: string;
  subArea?: string;
  type?: "home" | "office" | "other";
  default?: boolean;
  createdAt?: string;
}>;
// Variable: ALLCATEGORIES_QUERY
// Query: *[_type == 'category'] | order(name asc) [0...$quantity]
export type ALLCATEGORIES_QUERYResult = Array<{
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  range?: number;
  featured?: boolean;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
}>;
// Variable: ADMIN_CATEGORIES_QUERY
// Query: *[_type == 'category'] | order(title asc) {    _id,    title,    slug,    description,    featured  }
export type ADMIN_CATEGORIES_QUERYResult = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  description: string | null;
  featured: boolean | null;
}>;
// Variable: PRODUCT_BY_SLUG_QUERY
// Query: *[_type == "product" && slug.current == $slug] | order(name asc) [0]{    ...,    "averageRating": math::avg(*[_type == "review" && product._ref == ^._id && status == "approved"].rating),    "totalReviews": count(*[_type == "review" && product._ref == ^._id && status == "approved"])  }
export type PRODUCT_BY_SLUG_QUERYResult = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  images?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  description?: string;
  price?: number;
  discount?: number;
  categories?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "category";
  }>;
  stock?: number;
  brand?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "brand";
  };
  status?: "hot" | "new" | "sale";
  variant?: "appliances" | "gadget" | "others" | "refrigerators";
  isFeatured?: boolean;
  averageRating: number | null;
  totalReviews: number;
  ratingDistribution?: {
    fiveStars?: number;
    fourStars?: number;
    threeStars?: number;
    twoStars?: number;
    oneStar?: number;
  };
} | null;
// Variable: RELATED_PRODUCTS_QUERY
// Query: *[_type == "product" && count((categories[]._ref)[@ in $categoryIds]) > 0 && slug.current != $currentSlug] | order(name asc) [0...$limit]{    _id,    name,    slug,    price,    discount,    stock,    images,    categories[]->{      _id,      title,      slug    }  }
export type RELATED_PRODUCTS_QUERYResult = Array<{
  _id: string;
  name: string | null;
  slug: Slug | null;
  price: number | null;
  discount: number | null;
  stock: number | null;
  images: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }> | null;
  categories: Array<{
    _id: string;
    title: string | null;
    slug: Slug | null;
  }> | null;
}>;
// Variable: BRAND_QUERY
// Query: *[_type == "product" && slug.current == $slug]{"brandName": brand->title}
export type BRAND_QUERYResult = Array<{
  brandName: string | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "*[_type == 'order' && clerkUserId == $userId] | order(orderDate desc){\n  ...,products[]{\n    ...,product->\n  }\n}": QueryResult;
    "*[_type == 'product' && references(*[_type == \"category\" && slug.current == $categorySlug]._id)] | order(name asc)": PRODUCT_BY_CATEGORY_QUERYResult;
    "*[_type == 'sale'] | order(name asc)": SALE_QUERYResult;
    "*[_type == 'order' && clerkUserId == $userId] | order(orderDate desc)[$start...$end]{\n    ...,\n    paymentStatus,\n    paymentMethod,\n    products[]{\n      ...,\n      product->{\n        _id,\n        name,\n        slug,\n        image,\n        images,\n        price,\n        currency\n      }\n    }\n  }": MY_ORDERS_QUERYResult;
    "count(*[_type == 'order' && clerkUserId == $userId])": COUNT_QUERYResult;
    "*[_type == 'banner'] | order(publishedAt desc)": BANNER_QUERYResult;
    "*[_type == 'category' && featured == true] | order(name desc)": FEATURED_CATEGORY_QUERYResult;
    "*[_type==\"product\"] | order(name asc)": ALL_PRODUCTS_QUERYResult;
    "*[_type == 'product' && status == 'hot'] | order(name asc){\n  ...,\"categories\": categories[]->title\n}": DEAL_PRODUCTSResult;
    "*[_type == 'product' && isFeatured == true] | order(name asc){\n  ...,\"categories\": categories[]->title\n}": FEATURE_PRODUCTSResult;
    "*[_type=='brand'] | order(name asc) ": BRANDS_QUERYResult;
    " *[_type == 'blog' && isLatest == true]|order(name asc){\n    ...,\n    blogcategories[]->{\n    title\n  }\n  }": LATEST_BLOG_QUERYResult;
    "*[_type == 'blog'] | order(publishedAt desc)[0...$quantity]{\n  ...,  \n     blogcategories[]->{\n    title\n}\n    }\n  ": GET_ALL_BLOGResult;
    "*[_type == \"blog\" && slug.current == $slug][0]{\n  ..., \n    author->{\n    name,\n    image,\n  },\n  blogcategories[]->{\n    title,\n    \"slug\": slug.current,\n  },\n}": SINGLE_BLOG_QUERYResult;
    "*[_type == \"blog\"]{\n     blogcategories[]->{\n    ...\n    }\n  }": BLOG_CATEGORIESResult;
    "*[\n  _type == \"blog\"\n  && defined(slug.current)\n  && slug.current != $slug\n]|order(publishedAt desc)[0...$quantity]{\n...\n  publishedAt,\n  title,\n  mainImage,\n  slug,\n  author->{\n    name,\n    image,\n  },\n  categories[]->{\n    title,\n    \"slug\": slug.current,\n  }\n}": OTHERS_BLOG_QUERYResult;
    "*[_type==\"address\"] | order(publishedAt desc)": ADDRESS_QUERYResult;
    "*[_type == 'category'] | order(name asc) [0...$quantity]": ALLCATEGORIES_QUERYResult;
    "*[_type == 'category'] | order(title asc) {\n    _id,\n    title,\n    slug,\n    description,\n    featured\n  }": ADMIN_CATEGORIES_QUERYResult;
    "*[_type == \"product\" && slug.current == $slug] | order(name asc) [0]{\n    ...,\n    \"averageRating\": math::avg(*[_type == \"review\" && product._ref == ^._id && status == \"approved\"].rating),\n    \"totalReviews\": count(*[_type == \"review\" && product._ref == ^._id && status == \"approved\"])\n  }": PRODUCT_BY_SLUG_QUERYResult;
    "*[_type == \"product\" && count((categories[]._ref)[@ in $categoryIds]) > 0 && slug.current != $currentSlug] | order(name asc) [0...$limit]{\n    _id,\n    name,\n    slug,\n    price,\n    discount,\n    stock,\n    images,\n    categories[]->{\n      _id,\n      title,\n      slug\n    }\n  }": RELATED_PRODUCTS_QUERYResult;
    "*[_type == \"product\" && slug.current == $slug]{\n\"brandName\": brand->title\n}": BRAND_QUERYResult;
  }
}
